# Generated by Django 4.0.3 on 2022-05-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='detail',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='detail',
            new_name='description',
        ),
    ]
