# Generated by Django 4.0.3 on 2022-04-20 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='slug',
        ),
    ]
