# Generated by Django 4.0.4 on 2022-04-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2022-04-16'),
        ),
    ]
