# Generated by Django 4.0.3 on 2022-04-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_belonging'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Belonging',
        ),
    ]
