# Generated by Django 4.0.4 on 2022-04-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todolist_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='16/04/2022'),
        ),
    ]
