# Generated by Django 4.0.4 on 2022-04-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todolist_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('detail', models.TextField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
