# Generated by Django 4.0.4 on 2022-04-16 15:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_category_todo_delete_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 16, 15, 23, 30, 746004, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 16, 15, 23, 30, 746004, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 15, 23, 30, 746004, tzinfo=utc)),
        ),
    ]
