# Generated by Django 4.0.3 on 2022-05-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=1, max_length=30, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
